### PR TITLE
Fix bolt store

### LINKED ISSUE #7: if producer "p" has consumer contracts, then those cids are listed also for non-existent producer
Test to catch the issue in `bolt_test.go`
```
func TestBoltSetTwoProducers(t *testing.T) {
	db, err := BoltFile(boltTempDir)
	defer db.Close()
	assert.NoError(t, err)
	st := NewBoltStore(db)
	defer cleanBolt(t, st)

	// verify that we dont have any producer contracts
	cids, err := st.ListProducerContracts("p", "f")
	assert.NoError(t, err)
	assert.Empty(t, cids)

	// add producer data
	err = st.SetProducerData("p", "f", []byte("data"))
	assert.NoError(t, err)

	// create consumer
	err = st.SetConsumerContract("p", "c1", "f", []byte("contract-c1"))
	assert.NoError(t, err)

	// producer should have the consumer contract
	cids, err = st.ListProducerContracts("p", "f")
	assert.NoError(t, err)
	assert.Contains(t, cids, "c1")

	// add new contract
	err = st.SetConsumerContract("p", "c2", "f", []byte("contract-c2"))
	assert.NoError(t, err)

	// producer should have both contracts
	cids, err = st.ListProducerContracts("p", "f")
	assert.NoError(t, err)
	assert.Contains(t, cids, "c1", "c2")

	// non existing producer shouldn't have any contracts
	cids, err = st.ListProducerContracts("p2", "f")
	assert.NoError(t, err)
	assert.NotContains(t, cids, "c1", "c2")
	assert.Empty(t, cids)
}
```

### PR DESCRIPTION
**Pull request by shusso**
this fixes #7

### CODE REVIEW

File: store/bolt.go [hunk 1]
```diff
@@ -70,9 +72,10 @@ func (bs BoltStore) SetConsumerContract(pid, cid, format string, contract []byte
 		if err != nil {
 			return err
 		}
-		if err := pcb.Put([]byte(cid), contract); err != nil {
+		if err := pcb.Put([]byte(fmt.Sprintf("%s:%s", pid, cid)), contract); err != nil {
```
Comment (nassor) [inline store/bolt.go]: Generate a function that generates the keys, like that:

https://github.com/contrato/contrato-server/blob/master/store/bolt.go#L43

File: store/bolt_test.go [hunk 2]
```diff
@@ -86,16 +86,10 @@ func TestBoltSetConsumerContract(t *testing.T) {
...
-	db.View(func(tx *bolt.Tx) error {
-		c := tx.Bucket(st.producerDataBucket).Bucket([]byte(st.producerConsumersSubBucket)).Cursor()
-		for k, _ := c.First(); k != nil; k, _ = c.Next() {
-			producerContracts = append(producerContracts, k)
-		}
-		return nil
-	})
-	assert.Contains(t, producerContracts, []byte("c1"))
-	assert.Contains(t, producerContracts, []byte("c2"))
+	producerContracts, err := st.ListProducerContracts("p", "f")
```
Comment (nassor) [inline store/bolt_test.go]: You are expecting that the ListProducerContract function is working as expected, instead to check if the files are stored correctly.
